### PR TITLE
Stop loading patients not assigned to the current facility in the alphabetical patient log

### PR DESCRIPTION
**Pull request by vinaysshenoy**

### CODE REVIEW

**Comment by msasikanth** [comment]
@Honey14 While merging this, please make sure to drop the first commit in this PR.

**Comment by vinaysshenoy** [comment]
> @Honey14 While merging this, please make sure to drop the first commit in this PR.

Whoops, thanks for catching this! I completely forgot to drop this before raising it for review. Will fix tomorrow first thing.

**Comment by vinaysshenoy** [comment]
> > @Honey14 While merging this, please make sure to drop the first commit in this PR.
> 
> Whoops, thanks for catching this! I completely forgot to drop this before raising it for review. Will fix tomorrow first thing.

This is also why the instrumented CI checks are failing because the checks depend on the generated user being approved for syncing, which is done automatically on `QA` but not on `SANDBOX`.

**Review by Honey14 — APPROVED** [review]
Looks good

**Pull request merged**
