### PR TITLE
Add Sidama translations to Simple

### PR DESCRIPTION
**Pull request by msasikanth**
https://app.clubhouse.io/simpledotorg/story/3770/add-sidama-translations-to-simple

### CODE REVIEW

**Review by vinaysshenoy — DISMISSED** [review]

**Comment by vinaysshenoy** [comment]
@msasikanth Looks like Lint is failing. Would you be able to take a look?

**Comment by msasikanth** [comment]
> 
> 
> @msasikanth Looks like Lint is failing. Would you be able to take a look?

Yep fixed it, I forgot to push the changes that resolved those lint errors 😅

**Comment by vinaysshenoy** [comment]
@msasikanth Looks like another check has failed. Would you be able to take a look?

**Comment by msasikanth** [comment]
> @msasikanth Looks like another check has failed. Would you be able to take a look?

Ughh, I think it's because of the formatting. The translated strings file moved the comments around to the same line as a string. So that must have caused the issues with the string reader script.

**Review by vinaysshenoy — APPROVED** [review]

**Pull request merged**
