### PR TITLE
Use `PrescriptionRepository#refill` to refill prescriptions from edit medicines screen

### PR DESCRIPTION
**Pull request by msasikanth**
https://app.shortcut.com/simpledotorg/story/8890/run-prescription-refill-queries-in-a-transaction

### CODE REVIEW

**Comment by msasikanth** [comment]
Current dependencies on/for this PR:
* master
  * **PR #4147** <a href="https://app.graphite.dev/github/pr/simpledotorg/simple-android/4147" target="_blank">Graphite</a> 
    * **PR #4148** <a href="https://app.graphite.dev/github/pr/simpledotorg/simple-android/4148" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/simpledotorg/simple-android/4148?utm_source=stack-comment).

**Review by Honey14 — APPROVED** [review]

**Review by janhavisinghh — APPROVED** [review]
Approving this PR as Honey had already approved it

**Comment by janhavisinghh** [comment]
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/simpledotorg/simple-android/4148?utm_source=stack-comment).


Job Reference: DXoWU3Ev9lhr0fMSbTW7

**Comment by janhavisinghh** [comment]
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/simpledotorg/simple-android/4148?utm_source=stack-comment).


Job Reference: er7LDXuVEKZGZ1dDg4vu

**Pull request merged**
