### PR TITLE
Update CI checks to verify Clubhouse ticket links instead of Pivotal

### PR DESCRIPTION
**Pull request by vinaysshenoy**

### CODE REVIEW

**Comment by Honey14** [comment]
I think PR verification for clubhouse link is still not working fine. @vinaysshenoy 
Error : PR description doesn't contain a valid story link

**Comment by vinaysshenoy** [comment]
> I think PR verification for clubhouse link is still not working fine. @vinaysshenoy
> Error : PR description doesn't contain a valid story link

Which PR are you seeing this in?

**Comment by Honey14** [comment]
> Which PR are you seeing this in?

Here: https://github.com/simpledotorg/simple-android/pull/1463/checks?check_run_id=849034638

**Comment by vinaysshenoy** [comment]
> > Which PR are you seeing this in?
> 
> Here: https://github.com/simpledotorg/simple-android/pull/1463/checks?check_run_id=849034638

Hmm, this is weird. I'll have to check this out.

In any case, the check is not mandatory so it does not stop us from merging PRs.

**Pull request merged**
