### PR TITLE
Use `app:srcCompat` for `ImageView`

### PR DESCRIPTION
**Pull request by msasikanth**

### CODE REVIEW

**Comment by vinaysshenoy** [comment]
@msasikanth I am assuming that you've already run this on an API 21 emulator and verified that things are fine.

**Comment by msasikanth** [comment]
> @msasikanth I am assuming that you've already run this on an API 21 emulator and verified that things are fine.

I have run on API 23 emulator since development build is not installing on API 21. Is there a way for me to get around that?

**Comment by vinaysshenoy** [comment]
> > @msasikanth I am assuming that you've already run this on an API 21 emulator and verified that things are fine.
> 
> I have run on API 23 emulator since development build is not installing on API 21. Is there a way for me to get around that?

I meant on any emulator where the problem was reproducible, not API 21 specifically. If you have verified this, it looks good to me.

**Comment by msasikanth** [comment]
> I meant on any emulator where the problem was reproducible, not API 21 specifically. If you have verified this, it looks good to me.

Yeah, I have opened most of the screen which has `ImageView`s and where I made the changes and they are rendering fine without any issues.

**Pull request merged**
