### PR TITLE
Instant search screen improvements

### PR DESCRIPTION
**Pull request by msasikanth**
https://app.clubhouse.io/simpledotorg/story/4401/instant-search-screen-improvements

### CODE REVIEW

**Comment by vinaysshenoy** [comment]
Can we reword the PR title to specify what exactly are the changes we are making instead of having it be something vague like "Improvements"?

**Comment by msasikanth** [comment]
> Can we reword the PR title to specify what exactly are the changes we are making instead of having it be something vague like "Improvements"?

It has 2 different improvements to the instant search screen, I have broken them down in the changelog. Should I instead break down this PR into 2?

**Comment by vinaysshenoy** [comment]
> > Can we reword the PR title to specify what exactly are the changes we are making instead of having it be something vague like "Improvements"?
> 
> It has 2 different improvements to the instant search screen, I have broken them down in the changelog. Should I instead break down this PR into 2?

If the changes are unrelated apart from being done to the same screen, then yes.

**Comment by msasikanth** [comment]
Breaking this into 2 PRs

**Pull request closed without merging**
