### PR TITLE
Rename `OverdueAppointment` to `OverdueAppointment_Old`

### PR DESCRIPTION
**Pull request by msasikanth**
This PR also rename `OverdueAppointmentNew` to `OverdueAppointment`

### CODE REVIEW

**Comment by msasikanth** [comment]
Didn't update CHANGELOG as this change is feedback from earlier PR https://github.com/simpledotorg/simple-android/pull/3870

**Comment by janhavisinghh** [comment]
@msasikanth android tests seem to be failing in this can you ptal?

**Review by msasikanth — COMMENTED** [review]
> @msasikanth android tests seem to be failing in this can you ptal?

I have cleaned up Heroku instance. That should resolve the issue 🤞🏾

**Comment by msasikanth** [comment]
@janhavisinghh Android tests are passing now

**Review by janhavisinghh — APPROVED** [review]

**Pull request merged**
