### PR TITLE
Load overdue appointments when current facility is loaded and overdue sections feature is enabled

### PR DESCRIPTION
**Pull request by msasikanth**
https://app.shortcut.com/simpledotorg/story/8346/render-ui-for-all-overdue-sections-when-feature-flag-is-enabled

### CODE REVIEW

**Comment by msasikanth** [comment]
Current dependencies on/for this PR:
* master
  * **PR #3889** <a href="https://app.graphite.dev/github/pr/simpledotorg/simple-android/3889" target="_blank">Graphite</a> 
    * **PR #3890** <a href="https://app.graphite.dev/github/pr/simpledotorg/simple-android/3890" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/simpledotorg/simple-android/3890?utm_source=stack-comment).

**Review by Honey14 — APPROVED** [review]
LGTM

**Comment by msasikanth** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/simpledotorg/simple-android/3890?utm_source=stack-comment).


Job Reference: OnLo8O7RZS58UTIXGtOY

**Review by Honey14 — APPROVED** [review]
LGTM

**Review by Honey14 — APPROVED** [review]
LGTM

**Review by janhavisinghh — APPROVED** [review]

**Pull request merged**
