### PR TITLE
Update `ContactPatientBottomSheet` Behaviour to use the new `CallPatientView` 

### PR DESCRIPTION
**Pull request by janhavisinghh**
https://app.clubhouse.io/simpledotorg/story/3714/update-contactpatientbottomsheet-behaviour

Merge after #2810

### CODE REVIEW

**Comment by janhavisinghh** [comment]
@msasikanth this is ready for review

**Comment by vinaysshenoy** [comment]
Can we please avoid vague PR names like "Update `ContactPatientBottomSheet `-Final" and be specific about what changes are happening as part this PR?

**Review by msasikanth — CHANGES_REQUESTED** [review]
Left few comments PTAL. Also, it looks like we are not showing transferred from the label in the contact sheet. Please refer to the PRD for more explanation on it.

**Comment by msasikanth** [comment]
Also, it looks like the UI doesn't match the specs from Figma, PTAL at a couple of screenshots attached below.

screenshot-1626062914516

screenshot-1626062778453

**Comment by janhavisinghh** [comment]
Removed `switchToSetAppointmentReminderView_Old` and `switchToSetAppointmentReminderView` changes as we needed to hide both `callPatientView` and `callPatientView_Old` when that method was called. Hence, just added that as a new commit.

**Comment by janhavisinghh** [comment]
@msasikanth To display the transferred from facility name I will have to write a new migration to add the `patientAssignedFacilityName` in the `OverdueAppointment` database view. I'm planning to raise another small PR for it. Currently we are displaying the `assignedFacilityName` for both transferred from and registered at labels.

**Comment by msasikanth** [comment]
> @msasikanth To display the transferred from facility name I will have to write a new migration to add the `patientAssignedFacilityName` in the `OverdueAppointment` database view. I'm planning to raise another small PR for it. Currently we are displaying the `assignedFacilityName` for both transferred from and registered at labels.

We don't have to add assigned facility name column, we have to add registered facility name. Let's get on a short call, I just want to make sure we are all on same page about this.

**Comment by janhavisinghh** [comment]
As discussed offline I will raise another PR for transferred from facility implementation.

**Review by msasikanth — APPROVED** [review]
LGTM. There are still some layout margins and paddings that need to be adjusted, we can do that in the next PR.

**Pull request merged**
