### PR TITLE
Add support for prioritised nudges in `CheckAppUpdateAvailability`

### PR DESCRIPTION
**Pull request by janhavisinghh**
https://app.shortcut.com/simpledotorg/story/7225/add-support-for-prioritised-nudges-in-checkappupdateavailability

### CODE REVIEW

**Comment by janhavisinghh** [comment]
Waiting on the response to [this](https://docs.google.com/document/d/1Q3PwOTWKy3x5bAlPIBLCB1v7H4gR_FVJHVVqv-dX0sM/edit?disco=AAAAVntaOMM) question. As that would change the implementation a bit.

**Comment by janhavisinghh** [comment]
@msasikanth I've made all the changes we have discussed while pairing on this and this is ready for review now.

**Comment by janhavisinghh** [comment]
@msasikanth I've pushed with the changes we discussed. ptal?

**Review by msasikanth — APPROVED** [review]
LGTM. One question, how are we planning to pass the app version staleness information? Since that is required to render the days since last updated.

**Pull request merged**
