### PR TITLE
Remove maximum character limit for phone numbers

### PR DESCRIPTION
**Pull request by msasikanth**
https://app.clubhouse.io/simpledotorg/story/5018/remove-maximum-character-limit-for-phone-numbers

### CODE REVIEW

**Review by janhavisinghh — APPROVED** [review]
LGTM overall. Might be a nitpick but I was wondering why don't we have any validation check for special characters in phone number fields? Currently I can type `######` and it will pass as a valid phone number.

**Comment by msasikanth** [comment]
> LGTM overall. Might be a nitpick but I was wondering why don't we have any validation check for special characters in phone number fields? Currently I can type `######` and it will pass as a valid phone number.

This PR is just for removing the other length based number validations. Also, that we are just trying to keep it simple in terms of validation, that's the reason why we are removing the different length based validation for different countries.

**Review by janhavisinghh — APPROVED** [review]

**Comment by msasikanth** [comment]
reopening to see if the CI tests will be resolved

**Pull request closed without merging**
