### PR TITLE
Refactor `SignatureActivity`

### PR DESCRIPTION
**Pull request by msasikanth**

### CODE REVIEW

**Comment by msasikanth** [comment]
Waiting for #1743 to be merged in, to address some comments.

**Review by Honey14 — CHANGES_REQUESTED** [review]
PR looks good. The App crashes when trying to load the empty bitmap in the `init` function, not sure whether it is accepting empty bitmap. PTAL

**Comment by msasikanth** [comment]
> PR looks good. The App crashes when trying to load the empty bitmap in the `init` function, not sure whether it is accepting empty bitmap. PTAL

Good catch, fixed the issue. The library doesn't handle when setting null bitmaps. So in order to fix it if we load a `null` bitmap we do nothing now.

**Review by Honey14 — APPROVED** [review]
Looks good.

**Pull request merged**
