### PR TITLE
Neat logs for test(s) execution

### PR DESCRIPTION
**Pull request by ParanoidBeing**
`./gradlew clean test`

Screen Shot 2019-03-25 at 1 19 25 PM
Screen Shot 2019-03-25 at 1 19 52 PM

### CODE REVIEW

**Comment by pratul** [comment]
Hi @ParanoidBeing -- thank you for your very first contribution!

Please update your branch and delete the commit where you merge master into your feature branch? If your branch gets out of date, we expect you to rebase your branch against master. The reason we do this is so that the master branch remains clean and devoid of any references to personal branches of developers.

You can also automatically make this happen by applying the `autorebase` label to your PR.

**Comment by ParanoidBeing** [comment]
I think only people with write access can add labels? 

I have re-based the branch though.

**Comment by pratul** [comment]
Thanks; now that I've thought about it a bit... I don't think autorebase will work here, because your branch isn't (obviously :)) in this repository.

**Comment by pratul** [comment]
This looks good! Please squash the commits into one, and I'll merge.

**Pull request merged**
