### PR TITLE
Fix: Hide "free call" callout if masking is disabled

### PR DESCRIPTION
**Pull request by rakshakhegde**

### CODE REVIEW

**Comment by saket** [comment]
@rakshakhegde this PR contains untested logic. Please add a test?

**Comment by rakshakhegde** [comment]
@saket The logic is in UI. Should the part about the header also be in the controller? How to write the test?

**Comment by saket** [comment]
@rakshakhegde feature flags can live in the app for quite long, especially once we make them remote configurable. We should aim for always testing them to ensure we don't accidentally break the UI.

We could send the header item from the controller and ensure it only gets sent if the flag is enabled.

**Comment by vinaysshenoy** [comment]
@rakshakhegde There's a conflict here. Fix it?

**Comment by saket** [comment]
@rakshakhegde can we get this done today?

**Comment by rakshakhegde** [comment]
@saket This is what I'm working on right now.

**Comment by saket** [comment]
@rakshakhegde 🙂:+1:

**Comment by rakshakhegde** [comment]
@saket This PR has been updated. Please review.

**Pull request merged**
