### PR TITLE
Fix crash on edit medicines screen

### PR DESCRIPTION
**Pull request by vinaysshenoy**
https://app.clubhouse.io/simpledotorg/story/2047/dequeue-runnable-when-editmedicinesscreen-is-detached

# Steps to verify
- On `master`, change the delay to execute the recycler view scroll operation in `EditMedicinesScreen#populateDrugsList` to a larger value.
- Run the app and add a custom drug. Once the drug is added and before the earlier specified duration completes, press back and exit the `EditMedicinesScreen`.
- Once the delay is complete, the app will crash.
- Repeat the same task on the current branch

### CODE REVIEW

**Review by janhavisinghh — DISMISSED** [review]
LGTM

**Comment by vinaysshenoy** [comment]
@janhavisinghh If a PR is out of date or has conflicts when you're done reviewing, feel free to ask the author to resolve the conflicts. Otherwise, you'll need to approve this again later on.

**Comment by janhavisinghh** [comment]
> @janhavisinghh If a PR is out of date or has conflicts when you're done reviewing, feel free to ask the author to resolve the conflicts. Otherwise, you'll need to approve this again later on.

@vinaysshenoy I usually rebase and solve the merge conflicts if they're simple ones. Which is what I'm doing atm.

**Comment by vinaysshenoy** [comment]
> > @janhavisinghh If a PR is out of date or has conflicts when you're done reviewing, feel free to ask the author to resolve the conflicts. Otherwise, you'll need to approve this again later on.
> 
> @vinaysshenoy I usually rebase and solve the merge conflicts if they're simple ones. Which is what I'm doing atm.

Ah cool, I generally approve those after correcting them myself since GitHub dismisses PR review approvals if you update a PR afterwards.

**Review by janhavisinghh — APPROVED** [review]

**Pull request merged**
