### PR TITLE
Prepare `AuthenticationActivity` to use the new navigation framework

### PR DESCRIPTION
**Pull request by vinaysshenoy**
https://app.clubhouse.io/simpledotorg/story/2183/migrate-authenticationactivity-to-the-new-navigation-framework

### CODE REVIEW

**Review by Honey14 — CHANGES_REQUESTED** [review]
Looks good overall. overdue android tests are failing again :/

**Comment by vinaysshenoy** [comment]
> Looks good overall. overdue android tests are failing again :/

The only test that failed is one which verifies that the flaky test tool is working, which is itself flaky because it's intentionally random. Running the tests again should fix it.

**Comment by Honey14** [comment]
Hey @vinaysshenoy Can you try force-pushing? I've tried twice, it doesn't seem to be working

**Comment by vinaysshenoy** [comment]
> Hey @vinaysshenoy Can you try force-pushing? I've tried twice, it doesn't seem to be working

Force pushing will only force the jobs to rerun if the commit hash changes. Since the commit hash of HEAD has not changed, the actions will not be rerun. You'll need to go into the Actions UI and rerun the job from there.

**Comment by vinaysshenoy** [comment]
> > Hey @vinaysshenoy Can you try force-pushing? I've tried twice, it doesn't seem to be working
> 
> Force pushing will only force the jobs to rerun if the commit hash changes. Since the commit hash of HEAD has not changed, the actions will not be rerun. You'll need to go into the Actions UI and rerun the job from there.

Never mind, I see that the errors are different now. Will take a look.

**Comment by vinaysshenoy** [comment]
@Honey14 The tests have passed. Can you approve this, please?

**Review by Honey14 — APPROVED** [review]
Looks good

**Pull request merged**
