### PR TITLE
[WIP] Forgot PIN UI implementation

### PR DESCRIPTION
**Pull request by vinaysshenoy**

### CODE REVIEW

**Comment by saket** [comment]
@vinaysshenoy do you want to close this PR?

**Comment by vinaysshenoy** [comment]
@saket No. I am breaking out pieces of this PR for upcoming PRs. Can you merge in #261 please?

**Comment by saket** [comment]
@vinaysshenoy pratul is reviewing 261

**Comment by vinaysshenoy** [comment]
Closing this because is no longer necessary as all changes are now in #268.

**Pull request closed without merging**
