### PR TITLE
Truncate facility name

### PR DESCRIPTION
**Pull request by msasikanth**
https://www.pivotaltracker.com/story/show/171859083

### CODE REVIEW

**Comment by vinaysshenoy** [comment]
Instead of doing it in this manner, can we instead make it take up whatever space is available between the `Help` button and the rest of the screen? That should be more scalable across various devices.

**Comment by msasikanth** [comment]
> Instead of doing it in this manner, can we instead make it take up whatever space is available between the `Help` button and the rest of the screen? That should be more scalable across various devices.

I have tried doing that as well. I have to change layout `ViewGroup` because those were inside `Toolbar` I cannot set constraints. Is this ok, if I use `ConstraintLayout` inside the `Toolbar`?

```
    <androidx.constraintlayout.widget.ConstraintLayout
      android:layout_width="match_parent"
      android:layout_height="wrap_content">

      <Button
        android:id="@+id/facilitySelectButton"
        style="@style/Widget.AppCompat.Button.Borderless"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:drawableEnd="@drawable/ic_keyboard_arrow_down_24dp"
        android:drawablePadding="@dimen/spacing_4"
        android:ellipsize="end"
        android:maxLines="1"
        android:padding="@dimen/spacing_8"
        android:textAlignment="textStart"
        android:textAppearance="@style/Clinic.V2.TextAppearance.H6.White100"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toStartOf="@id/helpButton"
        app:layout_constraintHorizontal_chainStyle="spread_inside"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        tools:text="CHC Facility Name" />

      <Button
        android:id="@+id/helpButton"
        style="@style/Clinic.V2.ToolbarButton"
        android:layout_gravity="end"
        android:text="@string/home_help"
        android:textAppearance="@style/Clinic.V2.TextAppearance.Button2.White100"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toEndOf="@id/facilitySelectButton"
        app:layout_constraintTop_toTopOf="parent"
        tools:ignore="UnusedAttribute" />

    </androidx.constraintlayout.widget.ConstraintLayout>
```

**Comment by msasikanth** [comment]
> > Instead of doing it in this manner, can we instead make it take up whatever space is available between the `Help` button and the rest of the screen? That should be more scalable across various devices.
> 
> I have tried doing that as well. I have to change layout `ViewGroup` because those were inside `Toolbar` I cannot set constraints. Is this ok, if I use `ConstraintLayout` inside the `Toolbar`?
> 
> ```
>     <androidx.constraintlayout.widget.ConstraintLayout
>       android:layout_width="match_parent"
>       android:layout_height="wrap_content">
> 
>       <Button
>         android:id="@+id/facilitySelectButton"
>         style="@style/Widget.AppCompat.Button.Borderless"
>         android:layout_width="0dp"
>         android:layout_height="wrap_content"
>         android:drawableEnd="@drawable/ic_keyboard_arrow_down_24dp"
>         android:drawablePadding="@dimen/spacing_4"
>         android:ellipsize="end"
>         android:maxLines="1"
>         android:padding="@dimen/spacing_8"
>         android:textAlignment="textStart"
>         android:textAppearance="@style/Clinic.V2.TextAppearance.H6.White100"
>         app:layout_constraintBottom_toBottomOf="parent"
>         app:layout_constraintEnd_toStartOf="@id/helpButton"
>         app:layout_constraintHorizontal_chainStyle="spread_inside"
>         app:layout_constraintStart_toStartOf="parent"
>         app:layout_constraintTop_toTopOf="parent"
>         tools:text="CHC Facility Name" />
> 
>       <Button
>         android:id="@+id/helpButton"
>         style="@style/Clinic.V2.ToolbarButton"
>         android:layout_gravity="end"
>         android:text="@string/home_help"
>         android:textAppearance="@style/Clinic.V2.TextAppearance.Button2.White100"
>         app:layout_constraintBottom_toBottomOf="parent"
>         app:layout_constraintEnd_toEndOf="parent"
>         app:layout_constraintStart_toEndOf="@id/facilitySelectButton"
>         app:layout_constraintTop_toTopOf="parent"
>         tools:ignore="UnusedAttribute" />
> 
>     </androidx.constraintlayout.widget.ConstraintLayout>
> ```

and also since we are using `Button` we cannot set the gravity of the icon to be right beside the text. So the icon will be at the end of the button rather than wrapping in beside text.

Screenshot_1585198659

**Comment by vinaysshenoy** [comment]
> > > Instead of doing it in this manner, can we instead make it take up whatever space is available between the `Help` button and the rest of the screen? That should be more scalable across various devices.
> > 
> > 
> > I have tried doing that as well. I have to change layout `ViewGroup` because those were inside `Toolbar` I cannot set constraints. Is this ok, if I use `ConstraintLayout` inside the `Toolbar`?
> > ```
> >     <androidx.constraintlayout.widget.ConstraintLayout
> >       android:layout_width="match_parent"
> >       android:layout_height="wrap_content">
> > 
> >       <Button
> >         android:id="@+id/facilitySelectButton"
> >         style="@style/Widget.AppCompat.Button.Borderless"
> >         android:layout_width="0dp"
> >         android:layout_height="wrap_content"
> >         android:drawableEnd="@drawable/ic_keyboard_arrow_down_24dp"
> >         android:drawablePadding="@dimen/spacing_4"
> >         android:ellipsize="end"
> >         android:maxLines="1"
> >         android:padding="@dimen/spacing_8"
> >         android:textAlignment="textStart"
> >         android:textAppearance="@style/Clinic.V2.TextAppearance.H6.White100"
> >         app:layout_constraintBottom_toBottomOf="parent"
> >         app:layout_constraintEnd_toStartOf="@id/helpButton"
> >         app:layout_constraintHorizontal_chainStyle="spread_inside"
> >         app:layout_constraintStart_toStartOf="parent"
> >         app:layout_constraintTop_toTopOf="parent"
> >         tools:text="CHC Facility Name" />
> > 
> >       <Button
> >         android:id="@+id/helpButton"
> >         style="@style/Clinic.V2.ToolbarButton"
> >         android:layout_gravity="end"
> >         android:text="@string/home_help"
> >         android:textAppearance="@style/Clinic.V2.TextAppearance.Button2.White100"
> >         app:layout_constraintBottom_toBottomOf="parent"
> >         app:layout_constraintEnd_toEndOf="parent"
> >         app:layout_constraintStart_toEndOf="@id/facilitySelectButton"
> >         app:layout_constraintTop_toTopOf="parent"
> >         tools:ignore="UnusedAttribute" />
> > 
> >     </androidx.constraintlayout.widget.ConstraintLayout>
> > ```
> 
> and also since we are using `Button` we cannot set the gravity of the icon to be right beside the text. So the icon will be at the end of the button rather than wrapping in beside text.
> 
> Screenshot_1585198659

I think this is acceptable. Let's just get a signoff from design first.

**Comment by sanchita** [comment]
> > > > Instead of doing it in this manner, can we instead make it take up whatever space is available between the `Help` button and the rest of the screen? That should be more scalable across various devices.
> > > 
> > > 
> > > I have tried doing that as well. I have to change layout `ViewGroup` because those were inside `Toolbar` I cannot set constraints. Is this ok, if I use `ConstraintLayout` inside the `Toolbar`?
> > > ```
> > >     <androidx.constraintlayout.widget.ConstraintLayout
> > >       android:layout_width="match_parent"
> > >       android:layout_height="wrap_content">
> > > 
> > >       <Button
> > >         android:id="@+id/facilitySelectButton"
> > >         style="@style/Widget.AppCompat.Button.Borderless"
> > >         android:layout_width="0dp"
> > >         android:layout_height="wrap_content"
> > >         android:drawableEnd="@drawable/ic_keyboard_arrow_down_24dp"
> > >         android:drawablePadding="@dimen/spacing_4"
> > >         android:ellipsize="end"
> > >         android:maxLines="1"
> > >         android:padding="@dimen/spacing_8"
> > >         android:textAlignment="textStart"
> > >         android:textAppearance="@style/Clinic.V2.TextAppearance.H6.White100"
> > >         app:layout_constraintBottom_toBottomOf="parent"
> > >         app:layout_constraintEnd_toStartOf="@id/helpButton"
> > >         app:layout_constraintHorizontal_chainStyle="spread_inside"
> > >         app:layout_constraintStart_toStartOf="parent"
> > >         app:layout_constraintTop_toTopOf="parent"
> > >         tools:text="CHC Facility Name" />
> > > 
> > >       <Button
> > >         android:id="@+id/helpButton"
> > >         style="@style/Clinic.V2.ToolbarButton"
> > >         android:layout_gravity="end"
> > >         android:text="@string/home_help"
> > >         android:textAppearance="@style/Clinic.V2.TextAppearance.Button2.White100"
> > >         app:layout_constraintBottom_toBottomOf="parent"
> > >         app:layout_constraintEnd_toEndOf="parent"
> > >         app:layout_constraintStart_toEndOf="@id/facilitySelectButton"
> > >         app:layout_constraintTop_toTopOf="parent"
> > >         tools:ignore="UnusedAttribute" />
> > > 
> > >     </androidx.constraintlayout.widget.ConstraintLayout>
> > > ```
> > 
> > 
> > and also since we are using `Button` we cannot set the gravity of the icon to be right beside the text. So the icon will be at the end of the button rather than wrapping in beside text.
> > Screenshot_1585198659
> 
> I think this is acceptable. Let's just get a signoff from design first.

@msasikanth Can I suggest using `OmegaCenterIconButton` for the facility change button? 
That will let you set the icon at the end of the text.

**Comment by msasikanth** [comment]
> @msasikanth Can I suggest using `OmegaCenterIconButton` for the facility change button?
> That will let you set the icon at the end of the text.

Problem with that is it will also centre the facility name  🤔

**Comment by sanchita** [comment]
> > @msasikanth Can I suggest using `OmegaCenterIconButton` for the facility change button?
> > That will let you set the icon at the end of the text.
> 
> Problem with that is it will also centre the facility name 🤔 . Is there a way to not centre it in omega button?
Not sure. Will have to try it out and see.

**Comment by msasikanth** [comment]
> > > @msasikanth Can I suggest using `OmegaCenterIconButton` for the facility change button?
> > > That will let you set the icon at the end of the text.
> > 
> > 
> > Problem with that is it will also centre the facility name 🤔 . Is there a way to not centre it in omega button?
> 
> Not sure. Will have to try it out and see.

I have tried it. Setting `textAlignment` and `gravity` did not work.

**Pull request merged**
