### PR TITLE
Fix R8 build error when generating release artifacts

### PR DESCRIPTION
**Pull request by Honey14**
https://app.shortcut.com/simpledotorg/story/7391/fix-sandbox-build-failing-in-bitrise

### CODE REVIEW

**Comment by msasikanth** [comment]
Hmm, I agree with Sentry PR comment about this rule being too broad. We should probably look into only keep specific failing classes. WDYT?

**Comment by Honey14** [comment]
> Hmm, I agree with Sentry PR comment about this rule being too broad. Essentially that rule keeps all the enum classes in the project (our code and libraries) away from obfuscation.
> 
> We should probably look into only keep specific failing classes. WDYT?

That's probably a better idea. I'm not sure if this is the need of the moment though, WDYT? @msasikanth

**Comment by msasikanth** [comment]
You can use this Gradle command to test it out @janhavisinghh 
`./gradlew -PrunProguard=true assembleSandboxRelease bundleSandboxRelease`

**Review by janhavisinghh — APPROVED** [review]
LGTM

**Pull request merged**
