### PR TITLE
Use Automatic Rebase action

### PR DESCRIPTION
**Pull request by msasikanth**

### CODE REVIEW

**Comment by msasikanth** [comment]
Assiging this to @vinaysshenoy since @janhavisinghh already has few PRs to review and address.

**Comment by vinaysshenoy** [comment]
@msasikanth This does not seem to work yet, I'm guessing this is because we'll need to merge into master, right?

**Comment by msasikanth** [comment]
> @msasikanth This does not seem to work yet, I'm guessing this is because we'll need to merge into master, right?

Yes

**Review by vinaysshenoy — APPROVED** [review]

**Pull request merged**
