### PR TITLE
Change LoginPinScreen to use the remote PIN verification method

### PR DESCRIPTION
**Pull request by vinaysshenoy**
https://www.pivotaltracker.com/story/show/171874779

### CODE REVIEW

**Comment by rakshakhegde** [comment]
@vinaysshenoy Is this different from what I reviewed this morning? :P

**Comment by rakshakhegde** [comment]
Also, please assign to someone else?

**Comment by vinaysshenoy** [comment]
> @vinaysshenoy Is this different from what I reviewed this morning? :P

Yes. :P

**Comment by vinaysshenoy** [comment]
> Also, please assign to someone else?

I'll assign to @sanchita since she was on leave today. :P

**Comment by vinaysshenoy** [comment]
> The PR looks good. I hope you have tested this flow?

Yup, I've been testing them with each change.

**Pull request merged**
